# Generated by Django 5.1.1 on 2024-10-13 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_candidate_image_candidate_year_alter_candidate_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='election',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='dashboard.election'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='position',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='dashboard.position'),
        ),
    ]
