# Generated by Django 5.1.1 on 2024-10-13 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_candidate_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='election',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='dashboard.election'),
        ),
    ]
