# Generated by Django 5.1.1 on 2024-10-13 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_candidate_election_alter_candidate_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='election',
        ),
    ]
