# Generated by Django 5.1.1 on 2024-10-13 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_alter_candidate_election'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='election',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='dashboard.election'),
        ),
    ]
