# Generated by Django 5.1.1 on 2024-10-14 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_alter_candidate_election'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='year',
            field=models.CharField(choices=[('1st Year', '1st Year'), ('2nd Year', '2nd Year'), ('3rd Year', '3rd Year'), ('4th Year', '4th Year')], default='1st Year', max_length=20),
        ),
    ]
