# Generated by Django 5.1 on 2024-10-27 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_election_department_alter_student_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='department',
            field=models.CharField(choices=[('CS', 'Computer Science'), ('IT', 'Information Technology'), ('CE', 'Civil Engineering'), ('EE', 'Electrical Engineering'), ('ME', 'Mechanical Engineering'), ('BS', 'Business Studies'), ('HRM', 'Hospitality and Restaurant Management'), ('AB', 'Accountancy'), ('ED', 'Education'), ('Nursing', 'Nursing'), ('Architecture', 'Architecture'), ('Marine', 'Marine Engineering'), ('Chemistry', 'Chemistry'), ('Biology', 'Biology'), ('Physics', 'Physics'), ('Math', 'Mathematics'), ('Communication', 'Communication Arts'), ('Arts', 'Fine Arts'), ('Music', 'Music'), ('Law', 'Law'), ('ALL', 'ALL')], default='ALL', max_length=20),
        ),
    ]
