# Generated by Django 5.1 on 2024-10-27 09:58

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_alter_election_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='department',
        ),
        migrations.AddField(
            model_name='student',
            name='departments',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('CS', 'Computer Science'), ('IT', 'Information Technology'), ('CE', 'Civil Engineering'), ('EE', 'Electrical Engineering'), ('ME', 'Mechanical Engineering'), ('BS', 'Business Studies'), ('HRM', 'Hospitality and Restaurant Management'), ('AB', 'Accountancy'), ('ED', 'Education'), ('Nursing', 'Nursing'), ('Architecture', 'Architecture'), ('Marine', 'Marine Engineering'), ('Chemistry', 'Chemistry'), ('Biology', 'Biology'), ('Physics', 'Physics'), ('Math', 'Mathematics'), ('Communication', 'Communication Arts'), ('Arts', 'Fine Arts'), ('Music', 'Music'), ('Law', 'Law')], default=[], max_length=115),
        ),
    ]
