# Generated by Django 5.1 on 2024-10-27 12:04

import django.db.models.deletion
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_remove_student_department_student_departments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='election',
            name='department',
        ),
        migrations.RemoveField(
            model_name='student',
            name='departments',
        ),
        migrations.AddField(
            model_name='election',
            name='departments',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('CS', 'Computer Science'), ('IT', 'Information Technology'), ('CE', 'Civil Engineering'), ('EE', 'Electrical Engineering'), ('ME', 'Mechanical Engineering'), ('BS', 'Business Studies'), ('HRM', 'Hospitality and Restaurant Management'), ('AB', 'Accountancy'), ('ED', 'Education'), ('Nursing', 'Nursing'), ('Architecture', 'Architecture'), ('Marine', 'Marine Engineering'), ('Chemistry', 'Chemistry'), ('Biology', 'Biology'), ('Physics', 'Physics'), ('Math', 'Mathematics'), ('Communication', 'Communication Arts'), ('Arts', 'Fine Arts'), ('Music', 'Music'), ('Law', 'Law'), ('ALL', 'ALL')], default=['ALL'], max_length=119),
        ),
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.CharField(choices=[('CS', 'Computer Science'), ('IT', 'Information Technology'), ('CE', 'Civil Engineering'), ('EE', 'Electrical Engineering'), ('ME', 'Mechanical Engineering'), ('BS', 'Business Studies'), ('HRM', 'Hospitality and Restaurant Management'), ('AB', 'Accountancy'), ('ED', 'Education'), ('Nursing', 'Nursing'), ('Architecture', 'Architecture'), ('Marine', 'Marine Engineering'), ('Chemistry', 'Chemistry'), ('Biology', 'Biology'), ('Physics', 'Physics'), ('Math', 'Mathematics'), ('Communication', 'Communication Arts'), ('Arts', 'Fine Arts'), ('Music', 'Music'), ('Law', 'Law')], default='NULL', max_length=20),
        ),
        migrations.CreateModel(
            name='VoteSlip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votes', models.CharField(default='NULL', max_length=20)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voteslip', to='dashboard.election')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voteslip', to='dashboard.student')),
            ],
        ),
    ]
