# Generated by Django 5.1.1 on 2024-11-02 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_candidate_vote_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='course',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platforms', to='dashboard.candidate')),
            ],
        ),
    ]
