# Generated by Django 5.1.1 on 2024-11-02 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_candidate_course_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='platforms',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Platform',
        ),
    ]
