# Generated by Django 5.1 on 2024-11-25 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_candidate_platforms_delete_platform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voteslip',
            name='votes',
        ),
        migrations.AddField(
            model_name='voteslip',
            name='candidates',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='voteslip',
            name='election',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voteslips', to='dashboard.election'),
        ),
        migrations.AlterField(
            model_name='voteslip',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voteslips', to='dashboard.student'),
        ),
    ]
