# Generated by Django 5.1 on 2024-11-27 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_remove_voteslip_votes_voteslip_candidates_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='max_selection',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
