# Generated by Django 5.1 on 2024-11-28 04:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_position_max_selection'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='close_date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='election',
            name='open_date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
