# Generated by Django 5.1 on 2024-11-28 08:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_election_close_date_election_open_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='close_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='election',
            name='open_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
