# Generated by Django 5.1 on 2024-11-28 10:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_alter_election_close_date_alter_election_open_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='partylist',
            field=models.CharField(default=datetime.datetime.now, max_length=100),
        ),
    ]
