# Generated by Django 5.1 on 2024-11-28 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_candidate_partylist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='partylist',
            field=models.CharField(default='', max_length=100),
        ),
    ]
