# Generated by Django 5.1.1 on 2024-11-29 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_alter_candidate_partylist'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='is_winner',
            field=models.BooleanField(default=False),
        ),
    ]
